import type { Metadata } from "next";
import "@app/styles/globals.css";
import React from "react";
import { geistSans, geistMono } from "@shared/config/fonts";
import { Geist } from "next/font/google";
import { cn } from "@shared/lib/utils";
import { QueryProvider } from "@app/providers/QueryProvider";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="ru"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        "dark",
        geist.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
